require("themellowpea.launch")

-- NOTE: These are the LAZY_PLUGIN_SPECS

spec("themellowpea.plugins.alpha")
spec("themellowpea.plugins.autopairs")
spec("themellowpea.plugins.bufferline")
spec("themellowpea.plugins.colorizer")
spec("themellowpea.plugins.colorscheme")
spec("themellowpea.plugins.comment")
spec("themellowpea.plugins.diffview")
spec("themellowpea.plugins.dressing")
spec("themellowpea.plugins.formatting")
spec("themellowpea.plugins.git-blame")
spec("themellowpea.plugins.gitsigns")
spec("themellowpea.plugins.grug-far")
spec("themellowpea.plugins.harpoon")
spec("themellowpea.plugins.helpview")
spec("themellowpea.plugins.lazygit")
spec("themellowpea.plugins.linting")
spec("themellowpea.plugins.lualine")
spec("themellowpea.plugins.markdown-preview")
spec("themellowpea.plugins.marks")
spec("themellowpea.plugins.markview")
spec("themellowpea.plugins.maximizer")
spec("themellowpea.plugins.neotest")
spec("themellowpea.plugins.noice")
spec("themellowpea.plugins.numb")
spec("themellowpea.plugins.nvim-cmp")
spec("themellowpea.plugins.nvim-java")
spec("themellowpea.plugins.nvim-notify")
spec("themellowpea.plugins.nvim-tree")
spec("themellowpea.plugins.nvim-treesitter")
spec("themellowpea.plugins.nvim-surround")
spec("themellowpea.plugins.nvim-ufo")
spec("themellowpea.plugins.nvim-web-devicons")
spec("themellowpea.plugins.obsidian")
spec("themellowpea.plugins.project")
spec("themellowpea.plugins.schemastore")
spec("themellowpea.plugins.substitute")
spec("themellowpea.plugins.tmux-navigation")
spec("themellowpea.plugins.telescope")
spec("themellowpea.plugins.tiny-line-diagnostics")
spec("themellowpea.plugins.todo-comments")
spec("themellowpea.plugins.trouble")
spec("themellowpea.plugins.ts-comments")
spec("themellowpea.plugins.utils")
spec("themellowpea.plugins.which-key")
spec("themellowpea.plugins.vim-be-good")

-- NOTE: LSP CONFIG

spec("themellowpea.plugins.lsp.lspconfig")
spec("themellowpea.plugins.lsp.lsplens")
spec("themellowpea.plugins.lsp.lspsaga")
spec("themellowpea.plugins.lsp.mason")
spec("themellowpea.plugins.lsp.typescript-tools")

-- NOTE: Lazy loads last

require("themellowpea.lazy")
